# Generated by Django 4.2.14 on 2024-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('size', models.PositiveIntegerField()),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('website_name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('size', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=255, null=True)),
                ('website_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
